# Generated by Django 3.2.9 on 2021-11-20 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0003_auto_20211107_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='01-01-2000'),
        ),
        migrations.AlterField(
            model_name='event',
            name='decription',
            field=models.TextField(default='TBA', max_length=1024),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wydarzenio.place'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='TBA', max_length=128),
        ),
    ]
