# Generated by Django 3.2.9 on 2021-11-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0004_auto_20211120_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
