# Generated by Django 3.2.9 on 2021-11-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0005_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='decription',
            new_name='description',
        ),
    ]
