# Generated by Django 3.2.9 on 2021-11-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0006_rename_decription_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, upload_to='event/posters'),
        ),
    ]
