# Generated by Django 3.2.9 on 2021-11-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0008_alter_event_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/media/event/posters/tumblr_a4f6104f246a9fcd3c46f4212a1f9d9c_be7b3587_1280.png', null=True, upload_to='event/posters'),
        ),
    ]
