# Generated by Django 3.2.9 on 2021-12-21 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0010_auto_20211212_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventfileimport',
            name='file',
            field=models.FileField(upload_to='event/file_imports', validators=[django.core.validators.FileExtensionValidator(['ics', 'json'])]),
        ),
    ]
