# Generated by Django 3.2.9 on 2021-12-25 16:36

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0011_auto_20211221_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPatternInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(default='', max_length=1024)),
                ('iconPath', models.TextField(default='', max_length=1024)),
                ('colorHex', models.CharField(max_length=6)),
                ('lang', django_countries.fields.CountryField(default='ENG', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TechStackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(default='', max_length=1024)),
                ('icon', models.TextField(default='', max_length=1024)),
                ('lang', django_countries.fields.CountryField(default='ENG', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='eventfileimport',
            name='file',
            field=models.FileField(unique=True, upload_to='event/file_imports', validators=[django.core.validators.FileExtensionValidator(['ics', 'json'])]),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
