# Generated by Django 3.2.9 on 2021-12-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0012_auto_20211225_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(default='', max_length=1024)),
                ('lang', models.CharField(choices=[('Eng', 'English'), ('Pl', 'Polish')], default='Eng', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='designpatterninfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='designpatterninfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='designpatterninfo',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='designpatterninfo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='techstackinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='techstackinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='techstackinfo',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='techstackinfo',
            name='title',
        ),
        migrations.AddField(
            model_name='designpatterninfo',
            name='info_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wydarzenio.info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techstackinfo',
            name='info_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wydarzenio.info'),
            preserve_default=False,
        ),
    ]
