# Generated by Django 3.2.9 on 2021-12-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0013_auto_20211225_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpatterninfo',
            name='iconPath2',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
