# Generated by Django 3.2.9 on 2021-12-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0014_designpatterninfo_iconpath2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpatterninfo',
            name='iconPath2',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
