# Generated by Django 3.2.9 on 2021-12-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0018_remove_designpatterninfo_colorhex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperSingleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_call', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('was_succesfull', models.BooleanField(default=False)),
            ],
        ),
    ]
