# Generated by Django 3.2.9 on 2021-12-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0020_scrappersingleton_hours_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappersingleton',
            name='last_call',
            field=models.DateTimeField(),
        ),
    ]
