# Generated by Django 3.2.9 on 2021-12-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0021_alter_scrappersingleton_last_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrappersingleton',
            old_name='was_succesfull',
            new_name='was_successful',
        ),
    ]
