# Generated by Django 3.2.9 on 2021-12-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0022_rename_was_succesfull_scrappersingleton_was_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrappersingleton',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
