# Generated by Django 3.2.9 on 2021-12-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0023_scrappersingleton_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrappersingleton',
            name='hours_limit',
        ),
        migrations.AddField(
            model_name='scrappersingleton',
            name='minutes_limit',
            field=models.IntegerField(default=30),
        ),
    ]
