# Generated by Django 3.2.9 on 2021-12-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0024_auto_20211226_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture_can_be_updated',
            field=models.BooleanField(default=True),
        ),
    ]
