# Generated by Django 3.2.9 on 2021-12-27 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0026_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfileimport',
            name='file',
            field=models.FileField(unique=True, upload_to='event/file_imports', validators=[django.core.validators.FileExtensionValidator(['ics', 'json', 'zip', 'md', 'csv'])]),
        ),
    ]
