# Generated by Django 3.2.9 on 2022-01-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0028_auto_20220109_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event/posters'),
        ),
    ]
