# Generated by Django 3.2.9 on 2022-01-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0031_auto_20220114_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='discord_subscription_channel',
            new_name='discord_subscription',
        ),
    ]
