# Generated by Django 3.2.9 on 2022-01-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenio', '0032_rename_discord_subscription_channel_event_discord_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordchannel',
            old_name='channel_id',
            new_name='name',
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='channel_url',
            field=models.CharField(default='Testowy', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
