name: Cypress end-to-end
on:
  schedule:
    # runs tests every day at 4am
    - cron: "5 8 * * 5"
  push:
jobs:
  nightly:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run server
        run: |
          cd backend && ./manage.py runserver &
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          cd frontend
          npm ci
          npm install
          npm run start
      - name: Cypress nightly tests 🌃
        uses: cypress-io/github-action@v2
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
